parameters:
#    login_new.example.class: Login\NewBundle\Example

services:
#    login_new.example:
#        class: %login_new.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
